name: wildtp
version: '${version}'
main: io.github.zyb3rwolfi.wildtp.WildTp
api-version: '1.20'

commands:
  wild:
    description: Teleports you to a random location
    usage: /wild
    permission: wildtp.command.wild
    default: ''

permissions:
  wildtp.command.wild:
    description: "Access to /wild"
    default: not op
